//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinimaServer.Models.dbTechX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string id { get; set; }
        public string name { get; set; }
        public string subName { get; set; }
        public string path { get; set; }
        public string img { get; set; }
        public string description { get; set; }
        public string categoryId { get; set; }
    }
}
